version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./data/mongo:/data/db
  backend:
    build: ./backend
    container_name: backend
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - ENV=production